#!/usr/bin/python

import logger

logger.debug('123')
logger.error('Failed...')
